import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "../components/ui/sonner";
const roboto = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Healty Carely",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className=" md:px-20">
          <Header></Header>
          {children}
          <Toaster />

          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
